config/routes.rb
Rails.application.routes.draw do

  # get 'dashboards/show'
  devise_for :users
  # resources :users, only: [:create]

  root to: 'pages#home'
  get "/dashboard", to: "dashboards#show"
  resources :bookings, except: [:create, :index, :new, :update, :show] do
    resources :reviews, only: [:create, :new]
  end
  resources :beasts, only: [:create, :index, :new, :update, :show, :destroy] do
    resources :bookings, only: [:create, :new, :update, :destroy]
  end
end

app/views/shared/_background.html.erb
            <ul class="circles">
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
            </ul>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer text-center">
  <div class="d-flex justify-content-center"  >
    <div class="positon-absolute weas">
      <%= image_tag "weasley.jpg",  class: "avatar-weasley-1" %>
      <%= image_tag "weasley.jpg",  class: "avatar-weasley-2" %>
    </div>
  </div>
  <div>Weasley-Brothers.CO</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">


  <div class="d-flex">
    <%= link_to "https://airbnbeasts.herokuapp.com", class: "navbar-brand" do %>
      <%= image_tag "https://cdn11.bigcommerce.com/s-sq9zkarfah/images/stencil/1280x1280/products/74277/135809/Harry-Potter-Deathly-Hallows-Logo-Vinyl-Decal-Sticker__40234.1510890355.jpg?c=2?imbypass=on" %>
      <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <h1><%= link_to "airbnBEAST", root_path %></h1>
  </div>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? && current_user.first_name == "Harry Potter" %>
         <li class="nav-item ml-auto">
          <%= link_to current_user.first_name, dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://lh3.googleusercontent.com/0duXs46FK54NZtOAnXbqv5xcpz0NCf7JE34ITfYZhGS2eiPWd11l9FzaJNEnny1K1Fatz2oE2HENKahpPQ=rw", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% elsif user_signed_in? && current_user.first_name == "Hermione Granger" %>
          <li class="nav-item ml-auto">
            <%= link_to current_user.first_name, dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <%= image_tag "https://images-na.ssl-images-amazon.com/images/I/81Z9f1Kos%2BL._SY679_.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Book a beast", beasts_path, class: "dropdown-item" %>
            <%= link_to "Rent out a beast", new_beast_path, class: "dropdown-item" %>
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<div class="top-margin"></div>

app/views/shared/_promo.html.erb
<% if beast.promo %>
  <div class="minus">
    <h3>-<%= beast.promo %>%</h3>
  </div>
<% end %>

app/views/shared/_research.html.erb
<!-- # to do create research method in beast controller -->
<div class="form-group">
  <%= form_tag beasts_path, method: :get, class: "form-search" do %>
    <%= text_field_tag :query, params[:query], placeholder: "Search Beast", class: "form-control form-group" %>

    <button name="button" type="submit" class="btn-search">
      <i class="fas fa-search"></i>
    </button>
    <div class="radio-buttons mr-1">
      <%= radio_button_tag :sorting, "price" %>
      <span class="mr-5"><%= label_tag(:price, "Low-high prices") %></span>
      <%= radio_button_tag :sorting, "dangerosity" %>
      <span><%= label_tag(:dangerosity, "Danger Rating") %></span>
    </div>
  <% end %>
</div>

app/views/shared/_valentin.html.erb
<div class="badge">
 <span class="heart"> </span>
 <h1>Saint Valentin <br> -50%</h1>
 <h3>sur les dragons</h3>
</div>