config/routes.rb
Rails.application.routes.draw do

  # get 'dashboards/show'
  devise_for :users
  # resources :users, only: [:create]

  root to: 'pages#home'
  get "/dashboard", to: "dashboards#show"
  resources :bookings, except: [:create, :index, :new, :update, :show] do
    resources :reviews, only: [:create, :new]
  end
  resources :beasts, only: [:create, :index, :new, :update, :show, :destroy] do
    resources :bookings, only: [:create, :new, :update, :destroy]
  end
end

app/models/beast.rb
class Beast < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  SPECIES = ["Owl", "Elf", "Basilisk", "Hungarian Horntail", "Fawke", "Dementor", "Goblin", "Troll", "Cerberus"]
  DANGEROSITIES = (1..5)
  PRICES = (15..150)

  has_many :bookings, dependent: :destroy

  has_many :reviews, through: :bookings, dependent: :destroy

  has_many :users, through: :bookings

  belongs_to :user


  include PgSearch::Model
  pg_search_scope :search,
                  against: [:name, :species, :price, :dangerosity],
                  using: {
                    tsearch: { prefix: true }
                  }

  validates :name, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :dangerosity, presence: true
  validates :price, presence: true
  validates :species, presence: true
end

app/controllers/beasts_controller.rb
class BeastsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @beasts = Beast.all

    @beasts = @beasts.order("#{params[:sorting]} ASC") if params[:sorting].present?

    if params[:query].present?
      @beasts = @beasts.search(params[:query])
    end
  end

  def show
    @beast = Beast.find(params[:id])
    @bookings = @beast.bookings
    @booking = Booking.where(user: current_user, beast: @beast).first
    @reviews = @beast.reviews
  end

  def create
    @beast = current_user.beasts.create!(beast_params)
    # @beast = Beast.new(beast_params)
    if @beast.save
      redirect_to beast_path(@beast)
    else
      render 'new'
    end
  end

  def new
    @beast = Beast.new
  end

  def destroy
    @beast = Beast.find(params[:id])
    @beast.destroy
    redirect_to dashboard_path
  end

  private

  def beast_params
    params.require(:beast).permit(:name, :description, :address, :dangerosity, :price, :species, :photo)
  end
end

app/views/beasts/create.html.erb
<div align="center" class="container">
    <a href="http://thelink" class="the-click"></a>
    <iframe wmode="Opaque" class="video-iframe" width="100%" height="315" src="//www.youtube.com/embed/ZauRZNs8BMg" frameborder="0" allowfullscreen="">
    </iframe>
</div>

app/views/beasts/index.html.erb
<div class="container-fluid d-flex justify-content mt-5">

</div>
<div class="banner">
  <div class="container search-form-control">
  <%= render 'shared/research' %>
    <div class="promo">
      <%= render 'shared/valentin' %>
    </div>
  </div>
</div>

<div class="cards-grid container-fluid d-flex flex-wrap justify-content-center align-items-center col-10 mt-5">

  <% @beasts.each do |beast| %>
      <div class="container-fluid col-4 mb-5">
        <div class="beast-card d-flex justify-content-center align-items-center" style="background-image: linear-gradient(180deg, rgba(212,255,199,0.3309698879551821) 0%, rgba(2,0,36,0.7175245098039216) 49%, rgba(134,36,36,0.15449929971988796) 100%), url('<%= image_path "#{beast.species}.jpg" %>')">
            <div>
             <%= render 'shared/promo', beast: beast %>
            </div>

            <div class="card-title text-center">
              <h4><%= beast.name %></h4>
              <div id="species">
                <i class="fas fa-dragon"></i>
                <%= beast.species %>
              </div>
            </div>
            <div class="mb-5 card-body" >
              <div class="m-3">
                <div class="mb-2">
                  <i class="fas fa-pound-sign"></i>
                  <% if beast.promo %>
                    <%= beast.price * beast.promo / 100 %>/day
                  <% else %>
                    <%=  beast.price %>
                  <% end %>
                </div>

                <div class="mb-2">
                  <div>DANGER</div>
                  <div>
                    <% beast.dangerosity.times do  %>
                     <%= image_tag('danger.png', class: "danger-avatar") %>
                    <% end %>
                  </div>
                </div>
                <div>
                  <i class="fas fa-map-pin"></i>
                  <%= beast.address %>
                </div>
              </div>
              <div class="container-fluid d-flex justify-content-center">
                <button><%= link_to 'More details', beast_path(beast) %></button>
              </div>
            </div>
        </div>

      </div>
  <% end %>
</div>

app/views/beasts/new.html.erb
<div class="container p-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Tell us everything about your beast</h1>

      <%= simple_form_for @beast do |f| %>
        <%= f.input :name %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.input :description, as: :text  %>
        <%= f.input :address %>
        <%= f.input :dangerosity, collection: Beast::DANGEROSITIES %>
        <%= f.input :price, label: 'Price (£/rental day)', error: 'We recommend you fix your price between £15 and £150' %>
        <%= f.input :species, collection: Beast::SPECIES %>
        <%= f.button :submit, class: 'btn' %>
      <% end %>
    </div>
  </div>
</div>

app/views/beasts/show.html.erb
<div class="d-flex flex-wrap " style="padding-top: 100px;">


  <div class="container d-flex flex-wrap col-6 justify-content-center align-items-top">

        <div class="container col-8">
            <div class="beast-image" style="background-image: linear-gradient(180deg, rgba(199,255,244,0.16541353383458646) 0%, rgba(2,0,36,0.5326505602240896) 49%, rgba(108,16,104,0.15449929971988796) 100%), url('<%= image_path "#{@beast.species}.jpg" %>')">
            </div>
        </div>


        <div class="show-card mb-3 justify-content-center col-4" >
          <div class="border-bottom dark">
            <h2><%= @beast.name %></h2>
            <p><i class="fas fa-dragon"></i> <%= @beast.species %></p>

            <p>
              <% if current_user == @beast.user %>
                <strong> This is YOUR beast</strong>
              <% else %>
                <strong>Owner is <%= @beast.user.first_name || @beast.user.email %></strong>
              <% end %>
            </p>
          </div>
            <div class="mt-3 mb-5"><p>Description: <%= @beast.description %></p>
              <p><i class="fas fa-pound-sign"></i> <%= @beast.price %>/day</p>
              <% if @beast.promo %>
                only <i class="fas fa-pound-sign"></i>
                <%= @beast.price * @beast.promo / 100 %>
                on valentine's day

              <% end %>
              <div>dangerosity:</div>
              <% @beast.dangerosity.times do %>
                <%= image_tag('danger.png', class: "danger-avatar-square") %>
                <% end %>
              <p><i class="fas fa-map-pin"></i> <%= @beast.address %></p>
            </div>
            <div class="mb-3">
              <% if current_user != @beast.user %>
              <%= link_to '📆 Check availabilities', new_beast_booking_path(@beast), class: "btn" %>
              <% end %>
            </div>
            <div class="mb-3">
              <% if @booking %>
                <%= link_to '🖋 Write reviews', new_booking_review_path(@booking), class: "btn" %>
              <% end %>
            </div>
            <div class="review-yo mb-3 mt-3 pl-3">
              <h3>Reviews</h3>
              <% if @reviews.any? %>
                <% @reviews.each do |review| %>
                <p class="d-block p-2">
                  <% review.stars.times do %>
                  <i class="fas fa-star"></i>
                  <% end %>
                  </p>
                <p class="d-block p-2"><%= review.content %></p>
                  <% end %>
              <% end %>
            </div>
        </div>

  </div>

  <div class="container-fluid  d-flex justify-content-center col-6">
      <% if current_user == @beast.user %>
        <div class="container  ">
            <h3> next Bookings </h3>
            <% @bookings.each do |booking| %>
              <div class="booking-card d-flex align-items-center justify-content-between">
                <span class="">
                  <h3><%= booking.user.first_name %></h3>
                </span>
                <span>
                  <div>
                    begin : <%= booking.start_date %>
                  </div>
                  <div>
                    end : <%= booking.end_date %>
                  </div>
                </span>
                  <div class="d-flex">
                    <% if booking.status %>
                      <span> 🐲 </span>
                      <% else %>
                        <span>
                          <%= simple_form_for [@beast, booking] do |f| %>
                            <%= f.input :status, as: :hidden, input_html: {value: true}%>
                            <%= f.submit "validate", class: "boutton" %>
                        </span>
                        <span class="boutton">
                          <%= link_to 'Delete',
                                beast_booking_path(@beast, booking),
                                  method: :delete,
                                    data: { confirm: 'Are you sure?' } %>
                        </span>
                      <% end %>
                    <% end %>
                  </div>
              </div>
            <% end %>
        </div>
      <% end %>
    </div>
</div>