config/routes.rb
Rails.application.routes.draw do

  # get 'dashboards/show'
  devise_for :users
  # resources :users, only: [:create]

  root to: 'pages#home'
  get "/dashboard", to: "dashboards#show"
  resources :bookings, except: [:create, :index, :new, :update, :show] do
    resources :reviews, only: [:create, :new]
  end
  resources :beasts, only: [:create, :index, :new, :update, :show, :destroy] do
    resources :bookings, only: [:create, :new, :update, :destroy]
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
  end
end

app/views/dashboards/show.html.erb
<div class="container-fluid d-flex justify-content mt-5">
</div>

  <div class="d-flex">
    <div class="m-3 col-6">
      <div class="container d-flex justify-content-start align-items-stretch m-0 col-12 flex-column">
          <ul class="nav nav-tabs list-inline tabs-underlined" id="myTab" role="tablist">
            <li class="nav-item"><a href="#mybeasts" id="mybeasts-tab" data-toggle="tab" class="nav-link tab-underlined active">My Beasts</a></li>
            <li class="nav-item"><a href="#requests" id="requests-tab" data-toggle="tab" class="nav-link tab-underlined">My requests</a></li>
          </ul>

        <div class="ml-3">
          <div class="tab-content" id="myTabContent">

              <div class="tab-pane fade show active" id="mybeasts" role="tabpanel" aria-labelledby="mybeasts-tab">
                <h2 class="mt-5" id="mybeasts">My Beasts</h2>
                <% current_user.beasts.each do |beast| %>
                <div class="card-product mt-3">
                  <%= image_tag "#{beast.species}.jpg"%>
                  <div class="card-product-infos">
                    <h2><%= beast.name %></h2>
                    <p><%= beast.description %></p>
                    <p><i class="fas fa-pound-sign"></i> You rent it for <strong><%= beast.price %>/day</strong></p>
                    <p><i class="fas fa-radiation-alt"></i> Evaluated menace <%= beast.dangerosity %>/5</p>
                    <p><i class="fas fa-map-pin"></i> Lives in <strong><%= beast.address %></strong></p>
                    <%= link_to 'View its bookings', beast_path(beast), class: "btn" %>
                    <%= link_to "Kill beast", beast_path(beast),
                        method: :delete,
                        data: { confirm: "Are you sure?" }, class: "btn" %>
                  </div>
                </div>
              <% end %>
              </div>

            <div class="tab-pane fade" id="requests" role="tabpanel" aria-labelledby="requests-tab">

            <h2 class="mt-5" id="requests">My Requests</h2>
            <% current_user.bookings.each do |booking| %>
              <div class="card-product mt-3">
                <%= image_tag "#{booking.beast.species}.jpg"%>
                <div class="card-product-infos">
                  <h2><%= link_to booking.beast.name, beast_path(booking.beast) %></h2>
                  <p> From <strong><%= booking.start_date %></strong> Until <strong><%= booking.end_date %></strong></p>
                  <p> <strong>Booking status</strong> <% if booking.status %>
                    💚
                    <% else %>
                    🔴
                    <% end %></p>
                </div>
            </div>
            <% end %>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>